


export const deleteFile = async () => {
    try {
        
    } catch (error) {
        
    }
}